version: "3.8"

services:
  node-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules # Exclude node_modules to prevent issues
    restart: always
    command: npm run dev

  ai-service:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    volumes:
      - ./ai:/usr/src/ai
    restart: always
    command: python app/main.py
