version: "3.8"
services:
  node-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - AI_SERVICE_URL=http://ai-service:8000
    depends_on:
      - ai-service
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules # Exclude node_modules from the host to container sync
    command: nodemon src/server.js
    restart: always

  ai-service:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ai:/usr/src/ai
    command: python app/main.py
    restart: always
